### ISSUE TITLE
Updated Schedule CSV for 2019 but still not working

### ISSUE THREAD

**Issue by poonasor** [jclarke0000/MMM-MyWastePickup#4]
Updated the CSV for 2019 but the module is still stuck on Loading..

**Comment by TDMPro2K** [comment]
I also have this issue. I have installed and used everything as default but changed the date on the csv file so its 2019. Still says loading so I suspect something it broke somewhere....

**Comment by poonasor** [comment]
fixed it.

There were some years as 2019 which i've changed to 19 and removed the spaces on row 1

you can download it with the link above

**Comment by TDMPro2K** [comment]
I still get loading. I have loaded your csv and set it as Tuesday1, and it still says loading...
